### ISSUE TITLE
Tratamiento Prolongado

### ISSUE THREAD

**Issue by Rosmari-Montilla** [gesaodin/ipsfa-bss#18]
En Reembolso debera colocar un mensaje que indique su  cita ha sido programada para el día xxxxxxxx entre los cuales deberá asistir a la Gerencia de Droguería y Farmacia
Colocar status  Pendiente
		          Asistió

**Comment by gesaodin** [comment]
UPDATE: 4ad6e542b71ad460f5123e1f22057ba38d9804d3
