### ISSUE TITLE
Carga de archivos

### ISSUE THREAD

**Issue by Rosmari-Montilla** [gesaodin/ipsfa-bss#19]
Colocar en la carga de los archivos las siguentes acotaciones:
Los archivos deben ser cargados en ext PDF
Debe estar ordenado con un orden correlativo acorde al Informe Médico
Los documentos deben estar legible
El Informe medico deberá estar vigente

**Comment by gesaodin** [comment]
0e3ec3947e5a2ce40416a785d182916909ecfb0f
