### ISSUE TITLE
Menu Caso Generales 

### ISSUE THREAD

**Issue by Rosmari-Montilla** [gesaodin/ipsfa-bss#4]
Cambiar el titulo por:  Resumen de Solicitudes

**Comment by gesaodin** [comment]
Caso cerrado 

HEAD 35738f473f106f9ffe552d73de66f08202a2a2c1

**Comment by Rosmari-Montilla** [comment]
Le falto rcolocar un punto al final

**Comment by gesaodin** [comment]
Actualizado en h5 y se coloco el punto final 
UPDATE 8e0c026a6b28513b61e3de8a8b67b898b0674f0b
